### ISSUE TITLE
No Live Playlist? It's empty?

### ISSUE THREAD

**Issue by TheSangral** [DennisvHest/MapMaven#209]
I'm relatively new to the program so I don#t know if it's on me, but if I click on live playlist, it's just empty. There is nothing? Is something broken currently?

![Screenshot 2024-08-17 141203](https://github.com/user-attachments/assets/10752b3f-d246-41c1-b9df-ab53d4a5aeb1)

**Comment by DennisvHest** [comment]
Hey @TheSangral, thanks for trying out Map Maven.

The buttons in the playlist list are filters. So clicking on the live playlists button will only show live playlists, and vice versa, clicking on the playlists button will show only regular playlists.

Since you don't have a live playlist, none show up.

More info here: https://github.com/DennisvHest/MapMaven?tab=readme-ov-file#live-playlists
Do note: I changed the UI of the playlist list just a week ago and I still have to update the videos.
